export const skillOptions = [
  {label: 'Plumber (Home Services)', value: 'Plumber'},
  {label: 'Electrician (Home Services)', value: 'Electrician'},
  {label: 'Carpenter (Home Services)', value: 'Carpenter'},
  {label: 'Painter (Home Services)', value: 'Painter'},
  {label: 'Welder (Fabrication)', value: 'Welder'},
  {label: 'Mechanic (Automobile)', value: 'Mechanic'},
  {label: 'Driver (Transport)', value: 'Driver'},
  {label: 'Gardener (Outdoor)', value: 'Gardener'},
  {label: 'AC Technician (Appliance Repair)', value: 'AC Technician'},
  {label: 'Tailor (Garment)', value: 'Tailor'},
  {label: 'House Cleaner (Cleaning)', value: 'House Cleaner'},
  {label: 'Cook (Culinary)', value: 'Cook'},
  {label: 'Security Guard (Security)', value: 'Security Guard'},
  {label: 'Mason (Construction)', value: 'Mason'},
  {label: 'Delivery Executive (Logistics)', value: 'Delivery Executive'},
  {label: 'Barber (Personal Care)', value: 'Barber'},
  {label: 'Technician (Electronics)', value: 'Technician'},
  {label: 'Furniture Assembler (Furniture)', value: 'Furniture Assembler'},
  {label: 'Pest Control Expert (Home Services)', value: 'Pest Control Expert'},
  {label: 'Beautician (Personal Care)', value: 'Beautician'},
];
