import colors from './colors';
import {
  heightPercentageToDP,
  widthPercentageToDP,
} from 'react-native-responsive-screen';
export const ERROR_DURATION = 2000;
export const ERROR_STYLE = {borderColor: colors.error};
export const HP = heightPercentageToDP;
export const WP = widthPercentageToDP;
export default {
  WELCOME_TO: 'WELCOME TO',
  GET_STARTED: 'GET STARTED',
  EMAIl: 'EMAIL',
  PASSWORD: 'PASSWORD',
  SIGN_IN: 'SIGN IN',
  SIGN_UP: 'SIGN UP',
  RESET_PASSWORD: 'RESET PASSWORD?',
  DONT_HAVE_ACCOUNT: "DON'T HAVE AN ACCOUNT?",
  PRIVACY_POLICIES: 'PRIVACY POLICIES',
  USER_NAME: 'USER NAME',
  USERNAME: 'USERNAME',
  EMAIL_ADDRESS: 'EMAIL ADDRESS',
  UNIQUE_PASSWORD: 'Unique password',
  ENTER_NEW_PASSWORD: 'Enter New password',
  CONFIRM_PASSWORD: 'CONFIRM PASSWORD',
  TERMS_AND_CONDITIONS: 'By creating an account you agree with all our ',
  AND_OUR: 'and our ',
  TERMS_OF_SERVICE: 'Terms of Service ',
  PRIVACY_POLICY: 'Privacy Policy.',
  ALREADY_ACCOUNT: 'Already have  an account? ',
  RESET_PASSWORD_: 'Reset Password',
  BACK: 'Back',
  NEXT: 'Next',
  SUBMIT: 'Submit',
  ENTER_REGISTER_EMAIL_TO_RESET:
    'Enter registered e-mail  address and use the unique password to reset your password',
  EMAIL_SENT: 'Email Sent!',
  PLEASE_CHECK_INBOX:
    'Please check your inbox and use the unique password to reset your password',
  RESET_PASSWORD_SUCCESSFUL: 'reset password Successful',
  CONGRATS_PASSWORD_SUCCESFUL:
    'Congratulations your password has been changed successfully',
  TAB_1: 'M DAY : 29',
  LEADERBOARD: 'LEADERBOARD',
  POS: 'POS',
  PLAYER: 'PLAYER',
  BALLS_HIT: 'BALLS HIT',
  EACH_DAY: 'EACH DAY',
  JUNE: 'JUNE',
  TIME: 'Time',
  DATE: 'Date',
  DAY: 'Day',
  MONTH: 'Month',
  NEXT_LEVEL: 'Next Level',
  BALLS_HIT_EACH_DAY: 'BALLS HIT EACH DAY',
  BALLS: 'Balls',
  CREATE_NEW_PASSWORD: 'Create new password',
  SEARCH_TEXT: 'SEARCH RANGES BY LOACTION',
  DEFAULT_RANGES: 'DEFAULT RANGES',
  BALLS_PURCHASED: 'BALLS PURCHASED',
  ALL_FIELD_REQUIRED: 'All fields are required',
  INVALID_EMAIL: 'Please enter a valid email',
  EMAIL_REQUIRED: 'Email field is required',
  INVALID_PASSWORD:
    'Must contain at least one number and one uppercase and lowercase letter and one special character.',
  PASSWORD_MATCH: 'Password and confirm password should be the same',
  INVALID_NAME: 'Please enter a valid name',
  ACCEPT_TC: 'Please accept the terms and conditions',
  NO_INTERNET_FOUND: 'No internet found',
  CONNECTION_TIME_OUT: 'Connection timeout.',
  LOGOUT: 'Logout',
  buyNow: 'Buy Now',
  viewMorePurchases: 'VIEW PREVIOUS PURCHASES',
  USER_NAME_PROFILE: 'Username',
  EMAIL: 'Email',
  enterConfirmation: 'Enter \n confirmation code',
  uniqueCode: 'Unique Code',
  resendCode: 'RESEND CODE',
  enterCode: 'Please enter a unique code',
  level: 'Level',
  PrivacyPolicy: 'Privacy Policy',
  terms: 'Terms and Conditions',
  ADDCARD: 'Add debit/credit CARD',
  CARD: 'Card Number',
  EXPDATE: 'EXPIRATION DATE',
  CVV: 'CVV',
  NOCARD: 'No card found please add a card.',
  ADNEWCARD: 'Add New card',
  SAVE: 'SAVE',
  errorCard: 'Please enter valid card number',
  errorDate: 'Please enter valid expiry date',
  errorCvv: 'Please enter valid cvv',
  CONGRATULATIONS: 'CONGRATULATIONS!',
  PAYMENTSUCESS: 'Your payment is successful.',
  UPDATE: 'UPDATE',
  EDIT: 'EDIT',
  DELETE: 'DELETE',
};
